title: Antivirus Web Shell Detection
id: fdf135a2-9241-4f96-a114-bb404948f736
description: Detects a highly relevant Antivirus alert that reports a web shell
date: 2018/09/09
modified: 2001/01/07
author: Florian Roth, Arnim Rupp
references:
    - https://www.nextron-systems.com/2019/10/04/antivirus-event-analysis-cheat-sheet-v1-7-2/
    - https://www.virustotal.com/gui/file/bd1d52289203866645e556e2766a21d2275877fbafa056a76fe0cf884b7f8819/detection
    - https://www.virustotal.com/gui/file/308487ed28a3d9abc1fec7ebc812d4b5c07ab025037535421f64c60d3887a3e8/detection
    - https://www.virustotal.com/gui/file/7d3cb8a8ff28f82b07f382789247329ad2d7782a72dde9867941f13266310c80/detection
tags:
    - attack.persistence
    - attack.t1100
    - attack.t1505.003
logsource:
    product: antivirus
detection:
    selection:
        - Signature|startswith:
            - "PHP/Backdoor"
            - "JSP/Backdoor"
            - "ASP/Backdoor"
            - "Backdoor.PHP"
            - "Backdoor.JSP"
            - "Backdoor.ASP"
            - "Backdoor?Java"
        - Signature|contains:
            - "Webshell"
            - "Chopper"
            - "ASPXSpy"
            - "Aspdoor"
            - "PHP:"
            - "PHPShell"
            - "Trojan.PHP"
            - "Trojan.ASP"
            - "Trojan.JSP"
            - "PHP?Agent"
            - "ASP?Agent"
            - "JSP?Agent"
    condition: selection
fields:
    - FileName
    - User
falsepositives:
    - Unlikely
level: critical
